config/routes.rb
WeddingMenu::Application.routes.draw do



  resources :menu_items do
      	member do
			post 'bring'
			post 'buy'
      	end
      	collection do
      		get 'find'
  		end
  end

  resources :guests do
	 member do
		get 'partner_rsvp'
	 end
     collection do
		get 'find'
		post 'rsvp'
		get 'menu_rsvp'
     end
  end

  resources :menu_contributions





  root :to => "static#home"
  match "directions", :to => "static#directions", :as => :directions



end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :menu_items
end

app/models/guest.rb
class Guest < ActiveRecord::Base
	
	validates :name, :presence => true

	has_one :partner, :class_name => "Guest", :foreign_key => "partner_id"
end

app/models/menu_contribution.rb
class MenuContribution < ActiveRecord::Base
	#validates_inclusion_of :type, :in => ["paid", "made"]
	
	has_one :menu_item
	has_one :guest
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
	belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_guest
  
  def current_guest
  	@guest ||= Guest.find cookies[:guest_id] if cookies[:guest_id]
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
	
	def create
		@guest = Guest.new(params[:guest])
		
		if @guest.save
			Guest.find(@guest.partner_id).update_attributes(:partner_id => @guest.id) if @guest.partner_id
			render :json => @guest
		else
			render :status => 400, :text => @guest.errors.full_messages.to_sentence
		end
	end
	
	def rsvp
		
		if params[:guest][:id]
			@guest = Guest.find params[:guest][:id]
		else
			@guest = Guest.where(:name.matches => params[:guest][:name].gsub(/%/,"")).first
		end
		
		if @guest
			@guest.update_attributes(:is_rsvpd => true)
			
			cookies[:guest_id] = @guest.id unless current_guest
			
			render :json => @guest
		else
			render :nothing => true, :status => 404
		end
	end
	
	def partner_rsvp
		@guest = Guest.find params[:id]
		@partner = @guest.partner
		
		render :layout => false
	end
	
	def menu_rsvp
		@guest = current_guest
		
		render :layout => false
	end

	def find
		render :json => Guest.where(:name.matches => "#{params[:term]}%").map{ | g | g.name }
	end		
end

app/controllers/menu_contributions_controller.rb
class MenuContributionsController < ApplicationController
	
	def create
		@menu_contribution = MenuContribution.new(params[:menu_contribution])
		@menu_item = MenuItem.where(:name.matches => params[:menu_item][:name].gsub(/%/,"")).first
		
		@menu_item = MenuItem.create(params[:menu_item]) if @menu_item.nil?
		
		@menu_contribution.menu_item = @menu_item
		
		if @menu_contribution.save!
			flash[:thankyou] = "You wonderful, wonderful person!"
			redirect_to menu_items_url
		else
			flash[:error] = "Oh, something went wrong!"
			redirect_to new_menu_items_url
		end
		
	end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

	before_filter :get_menu_item, :only => [:bring, :buy]

	def index
		@courses = Course.all
	end
	
	def bring
		
	end

	def buy
	end
	
	def find
		render :json => MenuItem.where(:name.matches => "#{params[:term]}%").map{ | g | g.name }
	end
	
	def get_menu_item
		@menu_item = MenuItem.find params[:id]
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guest_helper.rb
module GuestHelper
end

app/helpers/menu_contributions_helper.rb
module MenuContributionsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
	
	def all_guest_food(guest)
		guest.menu_items + (guest.partner ? guest.partner.menu_items : [])
	end
	
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/guests/_menu_rsvp.html.erb
<p>Now the very important part: food! It would be absolutely awesome if you could bring some food along</p>

<p>There's a <%= link_to "list of lovely food ideas", menu_items_url %> if you're in need of some inspiration</p>

<% form_for :menu_contribution, :url => menu_contributions_url, :html => {:class => 'menuRsvp'} do | f | %>
	<%= f.hidden_field :guest_id, :value => guest.id %>
	<%= f.hidden_field :type, :value => "made"%>
	<p>Or if you've got an idea already, tell us!</p>
	
	<p class="userVoice">I'm going to bring <%= text_field :menu_item, :name, :class => "name" %> along, <%= f.submit "Because I'm fabulous" %>.</p>
	
<% end %>

app/views/guests/menu_rsvp.html.erb
<%= render :partial => "menu_rsvp", :locals => {:guest => @guest}%>

app/views/guests/partner_rsvp.html.erb
<div class="partnerRsvp">
	<strong>Awesome, glad you can come!</stong>
	
	<% if @partner && @partner.is_rsvpd %>
		<p>Looks like <%= @partner.name %> has already RSVP'd. We look forward to seeing the both of you soon!</p>
		
		<%= render :partial => "menu_rsvp", :locals => {:guest => @guest} %>
	<% elsif @partner %>
		<% form_for :guest, :url => rsvp_guests_url, :html => {:class => 'partnerRsvp'}, :method => :post do | f | %>
			<%= f.hidden_field :id, :value => @partner.id %>
			<%= f.hidden_field :is_rsvpd, :value => true %>
			Is <%= @partner.name %> coming too?&nbsp;<%= f.submit("Sure is") %>&nbsp;<button class="partnerSkip">No, can't make it!</button>
		<% end %>
	<% elsif @partner.nil? %>
		<% form_for :guest, :url => guests_url, :html => { :class => 'partnerCreate partnerRsvp' } do | f | %>
			<p class="error"></p>
			<%= f.hidden_field :partner_id, :value => @guest.id %>
			<%= f.hidden_field :is_rsvpd, :value => true %>
			<p>Do you have a significant other you'd like to bring?&nbsp;<button class="partnerSkip">Nope!</button><p>
			<p class="userVoice">I'm going to bring <%= f.text_field :name, :value => "" %>&nbsp;<%= f.submit "along too" %></p>
		<% end %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Getting married in a really big house in the country</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery', 'jquery-ui', 'jquery.easing', 'jquery.mousewheel', 'jquery.fancybox', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="header">
	<% if current_guest %>
		<div id="greeting">Hi <%= current_guest.name %>!</div>
	<% end %>
	<div id="primary-nav">
		<%= render 'shared/nav' %>
	</div>

	<div id="secondary-nav">
	</div>
</div>
<div id="container">
		<div id="content">
			<%= yield %>
		</div>
	<hr class="bottom" />
</div>

</body>
</html>

app/views/menu_items/_course.html.erb
<h1><%= course.name %></h1>

<ul>
	<%= render :collection => course.menu_items, :partial => 'menu_items/menu_item' %>
</ul>

app/views/menu_items/_menu_item.html.erb
<li><%= menu_item.name %>
	&nbsp;<%= link_to "I can bring this!", bring_menu_item_url(menu_item), :method => :post %>
	&nbsp;<%= link_to "I will pay #{number_to_currency(menu_item.price, :unit => '£')}  for this!", buy_menu_item_url(menu_item), :method => :post %>
</li>

app/views/menu_items/index.html.erb
<h1>The Picnic</h1>

<p>So there's going to be a really big picnic, if you bring the food for it!</p>

<p>Signup below if you want to make / bring something (there are suggestions for those who aren't sure)</p>

<% @courses.each do | course | %>
	<%= render :partial => 'menu_items/course', :locals => { :course => course } %>
<% end %>

app/views/shared/_nav.html.erb
<ul>
	<li><%= link_to "Home", root_url %></li>
	<li><%= link_to "Menu", menu_items_url %></li>
	<li><%= link_to "Sleeping", '#' %></li>
	<li><%= link_to "Where is this place", directions_url %></li>
</ul>